import type { Metadata } from "next";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import Providers from "@/app/providers";
import { LocaleDirectionSync } from "@/components/locale-direction-sync";
import { PageLoading } from "@/components/page-loading";
import { DirectionProvider } from "@/components/react-bits/ui/direction";
import { Toaster } from "@/components/react-bits/ui/sonner";
import { FavoritesMigrator } from "@/features/landing-page/components/favorites/favorites-migrator";
import { CustomCursor } from "@/features/landing-page/components/layout";
import { Navbar } from "@/features/landing-page/components/navbar";
import { settingsKeys } from "@/features/landing-page/lib/query-keys";
import { getDirection } from "@/i18n/locale";
import { routing } from "@/i18n/routing";
import { fontClassName } from "@/lib/fonts";
import { getQueryClient } from "@/lib/get-query-client";
import { getAppSettings } from "@/lib/settings-server";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const direction = getDirection(locale);

  return (
    <html lang={locale} dir={direction} className={fontClassName}>
      <body className="flex min-h-dvh flex-col">
        <Suspense fallback={<PageLoading />}>
          <LocaleLayoutContent locale={locale}>{children}</LocaleLayoutContent>
        </Suspense>
      </body>
    </html>
  );
}

async function LocaleLayoutContent({
  children,
  locale,
}: {
  children: React.ReactNode;
  locale: string;
}) {
  const messages = await getMessages();
  const direction = getDirection(locale);
  const queryClient = getQueryClient();
  const settings = await getAppSettings();

  queryClient.setQueryData(settingsKeys.all, settings);

  return (
    <>
      <Providers>
        <HydrationBoundary state={dehydrate(queryClient)}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <DirectionProvider dir={direction} key={locale}>
              <LocaleDirectionSync />
              <FavoritesMigrator />
              <CustomCursor />
              <Navbar />
              {children}
            </DirectionProvider>
          </NextIntlClientProvider>
        </HydrationBoundary>
      </Providers>
      <Toaster />
    </>
  );
}
